version: 2

builds:
  - id: fmp
    main: ./cmd/fmp
    binary: fmp
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - cmd: 'sh -c "if [ \"{{ .Os }}\" = \"linux\" ]; then upx -9 \"{{ .Path }}\"; fi"'
          output: true

archives:
  - id: fmp
    builds:
      - fmp
    name_template: "fmp_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: tobiash
    name: flux-manifest-preview
  prerelease: auto
