package filter

import (
	"testing"

	"sigs.k8s.io/kustomize/kyaml/yaml"
)

func TestFilterConfig_UnmarshalLabelRemover(t *testing.T) {
	input := `
filters:
  - kind: LabelRemover
    labels:
      - app.kubernetes.io/managed-by
`
	var fc FilterConfig
	if err := yaml.Unmarshal([]byte(input), &fc); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if len(fc.Filters) != 1 {
		t.Fatalf("expected 1 filter, got %d", len(fc.Filters))
	}
	lr, ok := fc.Filters[0].Filter.(*LabelRemover)
	if !ok {
		t.Fatal("expected LabelRemover filter")
	}
	if len(lr.Labels) != 1 || lr.Labels[0] != "app.kubernetes.io/managed-by" {
		t.Errorf("expected labels [app.kubernetes.io/managed-by], got %v", lr.Labels)
	}
}

func TestFilterConfig_UnmarshalUnknownKind(t *testing.T) {
	input := `
filters:
  - kind: DoesNotExist
`
	var fc FilterConfig
	err := yaml.Unmarshal([]byte(input), &fc)
	if err == nil {
		t.Fatal("expected error for unknown filter kind")
	}
}

func TestFilterConfig_UnmarshalMultipleFilters(t *testing.T) {
	input := `
filters:
  - kind: LabelRemover
    labels:
      - foo
      - bar
  - kind: LabelRemover
    labels:
      - baz
`
	var fc FilterConfig
	if err := yaml.Unmarshal([]byte(input), &fc); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if len(fc.Filters) != 2 {
		t.Fatalf("expected 2 filters, got %d", len(fc.Filters))
	}
}

func TestFilterConfig_UnmarshalFieldNormalizer(t *testing.T) {
	input := `
filters:
  - kind: FieldNormalizer
    match:
      kind: Secret
    fieldPaths:
      - path: [data, "tls.*"]
        action: replace
        placeholder: "<<auto-generated>>"
      - path: [sops]
        action: remove
`
	var fc FilterConfig
	if err := yaml.Unmarshal([]byte(input), &fc); err != nil {
		t.Fatalf("Unmarshal() error = %v", err)
	}
	if len(fc.Filters) != 1 {
		t.Fatalf("expected 1 filter, got %d", len(fc.Filters))
	}
	fn, ok := fc.Filters[0].Filter.(*FieldNormalizer)
	if !ok {
		t.Fatal("expected FieldNormalizer filter")
	}
	if fn.Match.Kind != "Secret" {
		t.Errorf("expected match.kind=Secret, got %q", fn.Match.Kind)
	}
	if len(fn.FieldPaths) != 2 {
		t.Fatalf("expected 2 field paths, got %d", len(fn.FieldPaths))
	}
	if len(fn.FieldPaths[0].Path) != 2 || fn.FieldPaths[0].Path[0] != "data" || fn.FieldPaths[0].Path[1] != "tls.*" {
		t.Errorf("expected first path [data, tls.*], got %v", fn.FieldPaths[0].Path)
	}
	if fn.FieldPaths[0].Action != ActionReplace {
		t.Errorf("expected action=replace, got %q", fn.FieldPaths[0].Action)
	}
	if fn.FieldPaths[1].Action != ActionRemove {
		t.Errorf("expected action=remove for sops, got %q", fn.FieldPaths[1].Action)
	}
}
