package filter

import (
	"encoding/base64"
	"fmt"
	"path"
	"strings"

	"sigs.k8s.io/kustomize/kyaml/kio"
	"sigs.k8s.io/kustomize/kyaml/yaml"
)

var _ kio.Filter = &FieldNormalizer{}

type FieldNormalizer struct {
	Kind       string        `yaml:"kind,omitempty"`
	Match      MatchCriteria `yaml:"match,omitempty"`
	FieldPaths []FieldPath   `yaml:"fieldPaths,omitempty"`
}

type MatchCriteria struct {
	Group         string `yaml:"group,omitempty"`
	Version       string `yaml:"version,omitempty"`
	Kind          string `yaml:"kind,omitempty"`
	Name          string `yaml:"name,omitempty"`
	Namespace     string `yaml:"namespace,omitempty"`
	HasAnnotation string `yaml:"hasAnnotation,omitempty"`
}

type FieldPath struct {
	Path        []string `yaml:"path"`
	Action      string   `yaml:"action,omitempty"`
	Placeholder string   `yaml:"placeholder,omitempty"`
}

const (
	ActionReplace = "replace"
	ActionRemove  = "remove"
	DefaultAction = ActionReplace
)

func (fn *FieldNormalizer) Filter(input []*yaml.RNode) ([]*yaml.RNode, error) {
	var result []*yaml.RNode
	for _, node := range input {
		if fn.matches(node) {
			for _, fp := range fn.FieldPaths {
				if err := fn.applyFieldPath(node, fp); err != nil {
					return nil, fmt.Errorf("applying field path %v: %w", fp.Path, err)
				}
			}
		}
		result = append(result, node)
	}
	return result, nil
}

func (fn *FieldNormalizer) matches(node *yaml.RNode) bool {
	m := fn.Match

	meta, err := node.GetMeta()
	if err != nil {
		return false
	}

	if m.Kind != "" && !globMatch(m.Kind, meta.Kind) {
		return false
	}
	if m.Group != "" {
		apiVersion := meta.APIVersion
		group := ""
		if idx := strings.Index(apiVersion, "/"); idx >= 0 {
			group = apiVersion[:idx]
		} else if apiVersion != "" {
			group = ""
		}
		if !globMatch(m.Group, group) {
			return false
		}
	}
	if m.Version != "" {
		apiVersion := meta.APIVersion
		ver := apiVersion
		if idx := strings.Index(apiVersion, "/"); idx >= 0 {
			ver = apiVersion[idx+1:]
		}
		if !globMatch(m.Version, ver) {
			return false
		}
	}
	if m.Name != "" && !globMatch(m.Name, meta.Name) {
		return false
	}
	if m.Namespace != "" && !globMatch(m.Namespace, meta.Namespace) {
		return false
	}
	if m.HasAnnotation != "" {
		annotations := meta.Annotations
		if _, ok := annotations[m.HasAnnotation]; !ok {
			found := false
			annPath := &yaml.PathGetter{Path: []string{"metadata", "annotations"}}
			annNode, err := node.Pipe(annPath)
			if err == nil && annNode != nil {
				fields, _ := annNode.Fields()
				for _, f := range fields {
					if globMatch(m.HasAnnotation, f) {
						found = true
						break
					}
				}
			}
			if !found {
				return false
			}
		}
	}

	return true
}

func (fn *FieldNormalizer) applyFieldPath(node *yaml.RNode, fp FieldPath) error {
	if len(fp.Path) == 0 {
		return nil
	}

	action := fp.Action
	if action == "" {
		action = DefaultAction
	}

	starIdx := -1
	for i, p := range fp.Path {
		if p == "[*]" {
			starIdx = i
			break
		}
	}

	if starIdx >= 0 {
		prefix := fp.Path[:starIdx]
		suffix := fp.Path[starIdx+1:]

		var arrNode *yaml.RNode
		var err error
		if len(prefix) == 0 {
			arrNode = node
		} else {
			arrNode, err = node.Pipe(&yaml.PathGetter{Path: prefix})
			if err != nil || arrNode == nil {
				return nil
			}
		}

		elements, err := arrNode.Elements()
		if err != nil || len(elements) == 0 {
			return nil
		}

		for _, elem := range elements {
			if len(suffix) == 0 {
				continue
			}
			innerFP := FieldPath{
				Path:        suffix,
				Action:      action,
				Placeholder: fp.Placeholder,
			}
			if err := fn.applyFieldPath(elem, innerFP); err != nil {
				return err
			}
		}
		return nil
	}

	lastKey := fp.Path[len(fp.Path)-1]
	parentPath := fp.Path[:len(fp.Path)-1]

	parentNode, err := node.Pipe(&yaml.PathGetter{Path: parentPath})
	if err != nil || parentNode == nil {
		return nil
	}

	isSecret := fn.isSecret(node)
	isDataField := fn.isDataField(fp)

	if containsGlob(lastKey) {
		fields, _ := parentNode.Fields()
		for _, field := range fields {
			if globMatch(lastKey, field) {
				if err := fn.applyAction(parentNode, field, action, fp.Placeholder, isSecret, isDataField); err != nil {
					return err
				}
			}
		}
		return nil
	}

	return fn.applyAction(parentNode, lastKey, action, fp.Placeholder, isSecret, isDataField)
}

func (fn *FieldNormalizer) applyAction(parentNode *yaml.RNode, key, action, placeholder string, isSecret, isDataField bool) error {
	switch action {
	case ActionRemove:
		_, err := parentNode.Pipe(&yaml.FieldClearer{Name: key})
		return err
	case ActionReplace:
		value := placeholder
		if value == "" {
			value = "<<auto-generated>>"
		}
		if isSecret && isDataField {
			value = base64.StdEncoding.EncodeToString([]byte(value))
		}
		return parentNode.PipeE(yaml.FieldSetter{Name: key, Value: yaml.NewScalarRNode(value)})
	default:
		return fmt.Errorf("unknown action %q", action)
	}
}

func (fn *FieldNormalizer) isSecret(node *yaml.RNode) bool {
	meta, err := node.GetMeta()
	if err != nil {
		return false
	}
	return meta.Kind == "Secret"
}

func (fn *FieldNormalizer) isDataField(fp FieldPath) bool {
	if len(fp.Path) == 0 {
		return false
	}
	return fp.Path[0] == "data" || fp.Path[0] == "stringData"
}

func containsGlob(pattern string) bool {
	return strings.ContainsAny(pattern, "*?[")
}

func globMatch(pattern, s string) bool {
	if pattern == "" || pattern == "*" {
		return true
	}
	matched, _ := path.Match(pattern, s)
	return matched
}
